[tool.ruff]
line-length = 88
select = ["E9", "F63", "F7", "F82"]
target-version = "py313"
exclude = [
    "starter_pack",
    "starter_pack copy",
    "node_modules",
    "web_app/node_modules",
    "web_app/dist",
]
