---
apiVersion: v1
kind: Namespace
metadata:
  name: script-ohio-prod
  labels:
    environment: production
    project: script-ohio
    version: v1
---
apiVersion: v1
kind: Namespace
metadata:
  name: script-ohio-monitoring
  labels:
    environment: production
    project: script-ohio
    version: v1
---
apiVersion: v1
kind: Namespace
metadata:
  name: script-ohio-logging
  labels:
    environment: production
    project: script-ohio
    version: v1